[package]
name = "rust-mongo-example"
version = "0.1.0"
authors = ["Mehmet Sefa BalÄ±k <mehmetsefabalik@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
r2d2-mongodb = "0.2.2"
r2d2 = "0.8.7"
mongodb = "0.3.12"
serde = "1.0.103"
futures = "0.1"